### ISSUE TITLE
Incorrect permissions on weights google drive link

### ISSUE THREAD

**Issue by tonydavis629** [Violet24K/SpherE#2]
Hi, I think you have to allow your google drive weights link to be open, they are currently not accessible publicly.

**Comment by Violet24K** [comment]
Thanks for reminding us. We just changed the permission so that anyone should be able to access it. 

Training a new model using the default configuration should result in a similar performance to the example weights.

**Comment by tonydavis629** [comment]
Much thanks. Very grateful for this paper and code.
